### ISSUE TITLE
Geting a 1 or 2 in IB score gen still gives you the Deploma

### ISSUE THREAD

**Issue by Jack17432** [blimpyazria/personal-site#6] opened 2020-09-22 04:32 UTC
![image](https://user-images.githubusercontent.com/44985312/93844398-1eaa0c00-fcf1-11ea-85f0-148ae9391410.png)

The Algarithem you use dose not check to see if the requirements are met for the IB score generator.

**Comment by blimpyazria** [comment] 2020-09-22 04:33
Duplicate of #2

**Closed by blimpyazria** 2020-09-22 04:33 UTC
